import NavBar from "@components/NavBar";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@components/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "AASTU ESCF",
  description: "Generated by create next app",
};

const navLinks = [
  { href: "/events", text: "Events" },
  { href: "/gallery", text: "Gallery" },
  { href: "/givings", text: "Givings" },
  { href: "/resources", text: "Resources" },
  { href: "/about", text: "About Us" },
  { href: "/contact", text: "Contact Us" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ height: "100%", width: "100%" }}>
      <body className={`${montserrat.className} h-full w-full`}>
        <NavBar navLinks={navLinks} />
        {children}
        <Footer navLinks={navLinks} />
      </body>
    </html>
  );
}
